import {test,expect} from 'bun:test';
import {createHash} from 'node:crypto';
import {parseCandidate} from '../src/intent/contract.ts';
import {resolveContext} from '../src/intent/resolve.ts';
import {contextFixture} from './context-fixture.ts';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
type Fixture=ReturnType<typeof contextFixture>;
// Pure future example IDs; these rows are not the user's policy confirmation or native data.
function answer(f:Fixture,id:number){const content=`Synthetic future confirmation ${id}`;const sourceId=`future-source-${id}`;f.rows.push({...f.rows[0]!,id,content});f.candidate.sources.push({...f.candidate.sources[0]!,id:sourceId,messageId:id,contentSha256:hash(content)});return sourceId;}
function lineage(merge=false){const f=contextFixture(),b=answer(f,2);f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:2,sourceIds:[b],supersedes:merge?[]:[1]});return f;}
function head(f:Fixture,sourceIds:string[],supersedes:number[]){f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:3,sourceIds,supersedes});return f;}
function refused(f:Fixture){expect(()=>parseCandidate(f.candidate)).toThrow('SUPERSESSION_NEEDS_NEW_SOURCE');const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('REJECTED');expect(r.requestedSelectionComplete).toBe(false);expect(r.decisions).toEqual([]);expect(r.gaps.some(g=>g.code==='SUPERSESSION_NEEDS_NEW_SOURCE')).toBe(true);}
test('R6 ancestor replay A1 -> B2 -> A3 rejects with valid retained rows',()=>{const f=lineage();refused(head(f,['synthetic-source'],[2]));});
test('R6 historical union merge A1 + B2 -> A/B3 rejects',()=>{const f=lineage(true);refused(head(f,['synthetic-source','future-source-2'],[1,2]));});
for(const merge of [false,true])test(`R6 genuinely new validated C beyond closure resolves merge=${merge}`,()=>{const f=lineage(merge),c=answer(f,3);head(f,[c],merge?[1,2]:[2]);const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('RESOLVED');expect(r.decisions.map(d=>d.revision)).toEqual([3]);expect(r.requestedSelectionComplete).toBe(true);expect(r.authority).toBe('NO_EXECUTION_AUTHORITY');});
for(const gap of ['missing-C','changed-C','missing-A','changed-B','false-C-sha'])test(`R6 novel C still preserves source byte gap ${gap}`,()=>{const f=lineage(),c=answer(f,3);head(f,[c],[2]);if(gap==='missing-C')f.rows.pop();else if(gap==='changed-C')f.rows[2]!.content+=' altered';else if(gap==='missing-A')f.rows.shift();else if(gap==='changed-B')f.rows[1]!.content+=' altered';else f.candidate.sources[2]!.contentSha256='0'.repeat(64);const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('NEEDS_EVIDENCE');expect(r.requestedSelectionComplete).toBe(false);expect(r.decisions).toEqual([]);});
for(const replay of ['alias','content-copy','immediate'])test(`R6 fake novelty ${replay} rejects`,()=>{const f=lineage();let s='future-source-2';if(replay==='alias'){f.candidate.sources.push({...f.candidate.sources[0]!,id:'future-alias'});s='future-alias';}else if(replay==='content-copy'){s=answer(f,3);f.rows[2]!.content=f.rows[0]!.content;f.candidate.sources[2]!.contentSha256=hash(f.rows[0]!.content);}refused(head(f,[s],[2]));});
test('R6 deep chain retains novel evidence and rejects replay of any ancestor',()=>{const f=lineage();for(let revision=3;revision<=12;revision++){const s=answer(f,revision);f.candidate.decisions.push({...f.candidate.decisions[0]!,revision,sourceIds:[s],supersedes:[revision-1]});}expect(resolveContext(f.candidate,f.request,f.rows).decisions.map(d=>d.revision)).toEqual([12]);f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:13,sourceIds:['future-source-3'],supersedes:[12]});refused(f);});
test('R6 ancestor missing target rejects through existing graph validation',()=>{const f=lineage();f.candidate.decisions[1]!.supersedes=[99];expect(()=>parseCandidate(f.candidate)).toThrow('INVALID_SUPERSESSION_TARGET');});
test('R6 cycle rejects through existing strict lower-revision graph validation',()=>{const f=lineage();f.candidate.decisions[0]!.supersedes=[2];expect(()=>parseCandidate(f.candidate)).toThrow('INVALID_SUPERSESSION_TARGET');});
test('R6 independent decision identity does not donate unrelated history',()=>{const f=contextFixture(),b=answer(f,2);f.candidate.decisions.push({...f.candidate.decisions[0]!,id:'future-independent',sourceIds:[b]});f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:2,sourceIds:[b],supersedes:[1]});const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('RESOLVED');expect(r.decisions).toHaveLength(2);});
test('R6 untouched unrelated topic gaps stay selective',()=>{const f=lineage(),c=answer(f,3);head(f,[c],[2]);f.candidate.sources.push({...f.candidate.sources[0]!,id:'future-unused',messageId:99});f.candidate.decisions.push({...f.candidate.decisions[0]!,id:'future-unselected',topic:'future-unrequested',sourceIds:['future-unused']});const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('RESOLVED');expect(r.sources.some(s=>s.id==='future-unused')).toBe(false);});
