import {test,expect} from 'bun:test';
import {createHash} from 'node:crypto';
import {resolveContext} from '../src/intent/resolve.ts';
import {parseRequest} from '../src/intent/contract.ts';
import {contextFixture} from './context-fixture.ts';
function correction(){const f=contextFixture();const content='Synthetic distinct answer';f.rows.push({...f.rows[0]!,id:2,content});f.candidate.sources.push({...f.candidate.sources[0]!,id:'new',messageId:2,contentSha256:createHash('sha256').update(content).digest('hex')});f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:2,sourceIds:['new'],supersedes:[1]});return f;}
test('R5 exact parent contradictory digest cannot counterfeit novelty',()=>{const f=contextFixture(),old=f.candidate.sources[0]!;f.candidate.sources.push({...old,id:'replayed-source'});old.contentSha256='0'.repeat(64);f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:2,statement:'Synthetic correction without a new answer.',sourceIds:['replayed-source'],supersedes:[1]});const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('REJECTED');expect(r.requestedSelectionComplete).toBe(false);expect(r.decisions).toEqual([]);});
test('R5 valid distinct message supersession',()=>{const f=correction();const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('RESOLVED');expect(r.decisions.map(d=>d.revision)).toEqual([2]);});
for(const mode of ['missing','changed','claimed-hash'])test(`R5 ${mode} predecessor evidence retained`,()=>{const f=correction();if(mode==='missing')f.rows.shift();else if(mode==='changed')f.rows[0]!.content+=' altered';else f.candidate.sources[0]!.contentSha256='0'.repeat(64);const r=resolveContext(f.candidate,f.request,f.rows);expect(r.status).toBe('NEEDS_EVIDENCE');expect(r.decisions).toEqual([]);expect(r.gaps.some(g=>g.subject==='synthetic-source')).toBe(true);});
test('R5 same anchor aliases do not supersede',()=>{const f=contextFixture();f.candidate.sources.push({...f.candidate.sources[0]!,id:'alias'});f.candidate.decisions.push({...f.candidate.decisions[0]!,revision:2,sourceIds:['alias'],supersedes:[1]});expect(resolveContext(f.candidate,f.request,f.rows).status).toBe('REJECTED');});
test('R5 unrequested missing evidence stays selective',()=>{const f=correction();f.candidate.sources.push({...f.candidate.sources[0]!,id:'other',messageId:99});f.candidate.decisions.push({...f.candidate.decisions[0]!,id:'other',topic:'unrequested',sourceIds:['other']});expect(resolveContext(f.candidate,f.request,f.rows).status).toBe('RESOLVED');});
for(const mode of ['getter','iterator','prototype','decoration'])test(`R5 bounded topics ${mode} refuses before caller code`,()=>{const f=contextFixture();let reads=0;const a:any=['placeholder'];if(mode==='getter')Object.defineProperty(a,'0',{get(){reads++;a.push(...Array.from({length:32},(_,i)=>'topic-'+i));return 'example-topic';}});else if(mode==='iterator')Object.defineProperty(a,Symbol.iterator,{get(){reads++;throw Error('iterator');}});else if(mode==='prototype')Object.setPrototypeOf(a,Object.create(Array.prototype));else a.extra='decoration';f.request.topics=a;expect(()=>parseRequest(f.request)).toThrow();expect(reads).toBe(0);});
